CC=g++
FLAGS=std=c++0x

main: main.cpp crewmanager.cpp date.cpp flight.cpp crewmember.cpp plane.cpp planemanager.cpp flightmanager.cpp
	$(CC) -$(FLAGS) -o main main.cpp crewmanager.cpp flight.cpp date.cpp crewmember.cpp plane.cpp planemanager.cpp flightmanager.cpp
